[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "devizzle"
version = "0.0.1"
authors = [
  { name="Wesley Barros", email="wesleybarros950@gmail.com" }
]
readme = "readme.md"
requires-python = ">=3.9"
