"""empty message

Revision ID: 6ef084e18cc3
Revises: 51ce0f96ab8e
Create Date: 2023-03-12 10:35:02.339046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef084e18cc3'
down_revision = '51ce0f96ab8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messaging_profiles', sa.Column('sent_count', sa.Integer(), nullable=True))
    op.add_column('messaging_profiles', sa.Column('received_count', sa.Integer(), nullable=True))
    op.add_column('messaging_profiles', sa.Column('reputation', sa.Integer(), nullable=True))
    op.add_column('messaging_profiles', sa.Column('ranking', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messaging_profiles', 'ranking')
    op.drop_column('messaging_profiles', 'reputation')
    op.drop_column('messaging_profiles', 'received_count')
    op.drop_column('messaging_profiles', 'sent_count')
    # ### end Alembic commands ###
