"""empty message

Revision ID: 73609499911f
Revises: f587669e0445
Create Date: 2023-03-24 17:40:30.857292

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73609499911f'
down_revision = 'f587669e0445'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
