"""empty message

Revision ID: 831eef7570b7
Revises: f695345430c4
Create Date: 2023-03-22 19:40:49.076254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '831eef7570b7'
down_revision = 'f695345430c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_disabled')
    # ### end Alembic commands ###
