"""removed password change stuff

Revision ID: bd13952ba8f8
Revises: aa65a21866ed
Create Date: 2023-03-25 08:53:29.305719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd13952ba8f8'
down_revision = 'aa65a21866ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_password_change_requests_id', table_name='password_change_requests')
    op.drop_index('ix_password_change_requests_secret_code', table_name='password_change_requests')
    op.drop_table('password_change_requests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_change_requests',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('secret_code', sa.VARCHAR(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_password_change_requests_secret_code', 'password_change_requests', ['secret_code'], unique=False)
    op.create_index('ix_password_change_requests_id', 'password_change_requests', ['id'], unique=False)
    # ### end Alembic commands ###
